/**
 * Jacobs document brand — the single source of every visual decision in
 * generated documents. See docs/DOC_GENERATION.md ("content ≠ presentation"):
 * the agent produces content and structure only; renderers apply this module.
 *
 * v1 derives from the app theme in app/globals.css (oklch tokens converted
 * to the sRGB hex documents need). When the official Jacobs brand guide
 * lands (palette, typeface, logo), swap the values here — every renderer
 * and the on-screen editor pick it up.
 *
 * Pure data + tiny helpers. Imported by client and renderers; no I/O.
 */

/** sRGB hex without "#", the format docx expects. */
export const BRAND_COLORS = {
  /** --primary oklch(0.45 0.13 255) — headings, cover band, table headers */
  primary: "17559b",
  /** --accent oklch(0.94 0.02 250) — callout fills, zebra rows */
  primaryTint: "e2edf8",
  /** --foreground oklch(0.18 0.025 255) — body text */
  ink: "0a121c",
  /** --muted-foreground oklch(0.5 0.02 250) — captions, footer, meta */
  inkMuted: "5c646f",
  /** --border oklch(0.912 0.012 250) — table borders, rules */
  hairline: "d9dfe5",
  /** --chart-2 oklch(0.65 0.11 220) — secondary accents only */
  accentTeal: "249ebd",
  /** --destructive — risk callout edge */
  risk: "d4453a",
  /** table header / cover band text */
  onPrimary: "ffffff",
} as const

export type BrandColor = keyof typeof BRAND_COLORS

export function brandHex(color: BrandColor): string {
  return `#${BRAND_COLORS[color]}`
}

/**
 * Typography (points). Arial/Helvetica in v1: licensed everywhere,
 * metric-safe, zero font-embedding work. The official Jacobs typeface is a
 * one-line swap per renderer family when brand supplies it.
 */
export const BRAND_TYPE = {
  /** docx font family */
  docxFont: "Arial",
  /** jspdf built-in family */
  pdfFont: "helvetica",
  coverTitle: 28,
  coverSubtitle: 13,
  h1: 16,
  h2: 13,
  h3: 11,
  body: 10,
  caption: 8.5,
  footer: 7,
  lineHeight: 1.15,
  /** space after a body paragraph, pt */
  paragraphSpacing: 6,
} as const

/**
 * Wordmark used on the cover until an approved logo asset is provided.
 * Reserve: replace with an image render keyed off BRAND_LOGO when available.
 */
export const BRAND_WORDMARK = { primary: "Jacobs", secondary: "Orbit Docs" } as const

/**
 * Honest-labeling footer required on every generated document. Enterprise
 * requirement, not a style choice — do not remove per-document.
 */
export const BRAND_DISCLAIMER =
  "AI-assisted draft generated by Orbit Docs — verify citations before external use"

/** Callout edge/label colors by tone. */
export const CALLOUT_TONES = {
  note: { edge: BRAND_COLORS.primary, label: "Note" },
  risk: { edge: BRAND_COLORS.risk, label: "Risk" },
  action: { edge: BRAND_COLORS.accentTeal, label: "Action" },
} as const

export type CalloutTone = keyof typeof CALLOUT_TONES

/** Tailwind-token classes for the on-screen editor, so screen ≈ print. */
export const CALLOUT_CLASSES: Record<CalloutTone, string> = {
  note: "border-l-primary bg-accent/60",
  risk: "border-l-destructive bg-destructive/5",
  action: "border-l-chart-2 bg-accent/40",
}
